###########################################
# PixieGrapplingHook by the PixieWorkshop #
###########################################

#-- Options --#

GrapplingHook:
    unbreakable: true
    speed: 2.0 # the force of the grappling hook #
    cooldown: 3 # in seconds #

    name: '&aGrappling Hook'
    lore: # Please use the ยง symbol when using color codes to lore lines #
        - 'ยง7Let out the grappling hook then'
        - 'ยง7reel it in to be pulled towards it!'

DisableFallDamage: true # Fall damage will be negated as long as the player is holding the grappling hook #

# Do Not Touch -_- #
config-version: 2